apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  cors-origin: {{ .Values.backend.config.corsOrigin | quote }}
  log-level: {{ .Values.backend.config.logLevel | quote }}
  python-unbuffered: {{ .Values.backend.config.pythonUnbuffered | quote }}